### ISSUE TITLE
Environment.prod.ts is part of the Typescript compilation but its unused.

### ISSUE THREAD

**Issue by hasnaalam2** [AmitXShukla/Online-School-Management-App-Angular-Firebase#11]

**Comment by hasnaalam2** [comment]
![Capture1](https://user-images.githubusercontent.com/61613356/76387304-9edbd600-638c-11ea-9bd1-86953388f1e9.PNG)
![Capture2](https://user-images.githubusercontent.com/61613356/76387313-a0a59980-638c-11ea-8169-6ef1198d468c.PNG)

**Comment by AmitXShukla** [comment]
1. Can you please show browser console as well
2. Please check your app.component.html and make sure it has <router-outlet></router-outlet> included
3. Please check your app-routing.ts file, I think, app is compiling fine, it's just something wrong with displaying first component.
4. If none of the options work for you, Is it possible, you can create a GitHub repo and send me a link of your source code so that I can look into all of your files and try to compile it on my machine and try to fix it for you.
