### ISSUE TITLE
Live notifications and Contact Form 

### ISSUE THREAD

**Issue by thotasirisha** [AmitXShukla/Online-School-Management-App-Angular-Firebase#16]
that issue is closed so i'm writing here, 

Sir, i changed the firebase rules as per requirement and now i can see all the data being uploaded is displayed correctly as per roles.. thankyou.  But i found 2 more issues now. 

**1.**  live notifications is not working.  Console is not showing any error.
 i tried changing the rules of match /SMS_USERS/{document} create, update, delete as true and tried, and also  
match /SMS_STUDENTS/{document}/notifications/{doc}   this function also.  
But still notifications are not displayed.  i attached firebase rules and console screenshot in the document. 

**2**  the contact form in the navbar , when details are filled and submitted, it says network connection error.  console shows error. plz see the document. 

https://docs.google.com/document/d/15jU3LIDnfH0a421bWkyzKCFrtCPEL9MN99DiwH-ogOU/edit?usp=sharing

**Comment by AmitXShukla** [comment]
Thanks for reaching out.

1. Notification related code does not exist in this repository.
Please see, this is a community version, hence lots of Pro version code is not shared.
I suggest you to please go through FireStore documentation for Cloud functions and write your own code.
What you want to write in this cloud function is, as soon as, a new notification document is entered by teacher/admin in notification collection, it takes that that notification and create a duplicate row and enter to individual student's (depending on grade level) collection. this way Students will see notification through their own record and you can change readReceipt=false after student read this one notification.
2. For email related API, You will see emailAPI: settings in your environment.ts file. 
Also If you see error closely, you will see email API url like - http://xxxxx/emailAPI.php
You will need to change this setting to your own SMTP API.
For similar reason, I can't share my own API for sending email because it cause tons of unwanted traffic to my website.

I hope this helps.
- Amit
